name: Build, Test, and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .netcore (6x, 7x, 8x)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x.x
            7.x.x
            8.x.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Sonar Scanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          testCommand: dotnet test .
          projectKey: "LHPiney_nuget_boiler_plate"
          projectName: "nuget_boiler_plate"
          sonarOrganisation: "lhpiney"
          beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
            /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pack
        run: dotnet pack --configuration Release --no-restore --output ./nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json